### ISSUE TITLE
Error while running event

### ISSUE THREAD

**Issue by stucker9** [Hermios/Factorio-Model#4]
http://prntscr.com/myai2x - Happens any time I try to place this combinator

**Comment by stucker9** [comment]
Want to apologize, that screenshot may not be totally helpful. I updated your mod but still have the issue, here is my current.log with more information: https://www.hastebin.com/umakohizoc.coffeescript

**Comment by Hermios** [comment]
HiI cannot really try, but it should be ok now!Thanks for this!
  

    Le samedi 16 mars 2019 à 12:39:36 UTC+1, Pwnographic <notifications@github.com> a écrit :  
 
 
Want to apologize, that screenshot may not be totally helpful. I updated your mod but still have the issue, here is my current.log with more information: https://www.hastebin.com/umakohizoc.coffeescript

**Comment by Hermios** [comment]
not enough information
